import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { RouterModule } from '@angular/router';
import { NbThemeModule, NbMenuModule, NbButtonModule, NbCardModule, NbInputModule, NbIconModule, NbSelectModule, NbToastrModule, NbDatepickerModule, NbDialogModule, NbTooltipModule, NbUserModule, NbCheckboxModule, NbRadioModule, NbAccordionModule, NbContextMenuModule, NbPopoverModule, NbStepperModule, NbListModule, NbTreeGridModule, NbActionsModule, NbSearchModule, NbSpinnerModule, NbTabsetModule, NbProgressBarModule, NbBadgeModule, NbAlertModule, NbChatModule, NbWindowModule, NbToggleModule, NbAutocompleteModule, NbCalendarModule } from '@nebular/theme';

@NgModule({
  imports: [
    NbThemeModule.forRoot({ name: 'default' }),
    NbMenuModule.forRoot(),
    NbButtonModule,
    NbCardModule,
    NbInputModule,
    NbIconModule,
    NbSelectModule,
    NbTooltipModule,
    NbUserModule,
    NbCheckboxModule,
    NbRadioModule,
    NbAccordionModule,
    NbContextMenuModule,
    NbPopoverModule,
    NbStepperModule,
    NbListModule,
    NbTreeGridModule,
    NbActionsModule,
    NbSearchModule,
    NbSpinnerModule,
    NbTabsetModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbAlertModule,
    NbChatModule,
    NbWindowModule,
    NbToggleModule,
    NbAutocompleteModule,
    NbCalendarModule,
  ],
  exports: [
    NbMenuModule,
    NbButtonModule,
    NbCardModule,
    NbInputModule,
    NbIconModule,
    NbSelectModule,
    NbToastrModule,
    NbDatepickerModule,
    NbDialogModule,
    NbTooltipModule,
    NbUserModule,
    NbCheckboxModule,
    NbRadioModule,
    NbAccordionModule,
    NbContextMenuModule,
    NbPopoverModule,
    NbStepperModule,
    NbListModule,
    NbTreeGridModule,
    NbActionsModule,
    NbSearchModule,
    NbSpinnerModule,
    NbTabsetModule,
    NbProgressBarModule,
    NbBadgeModule,
    NbAlertModule,
    NbChatModule,
    NbWindowModule,
    NbToggleModule,
    NbAutocompleteModule,
    NbCalendarModule,ReactiveFormsModule,MatFormFieldModule,RouterModule
  ],
})
export class NebularSharedModule {}
